### ISSUE TITLE
Добавить раздел про CORS

### ISSUE THREAD

**Issue by simgislab** [nextgis/docs_ngcom#1]
Вывести вот отсюда в свой подраздельчик:
http://docs.nextgis.ru/docs_ngcom/source/ngapi.html

1. Предложение про что это такое + ссылка на вики
1. Как в него попасть
1. Скриншот
1. Отсылка к тому что он доступен на плане Мини

**Comment by Kinda-me** [comment]
А как в него попасть и где взять скриншот?

**Comment by Kinda-me** [comment]
Такой скриншот?

![2017-07-02_19-13-01](https://user-images.githubusercontent.com/6493848/27771600-86e049c0-5f5a-11e7-8e28-9862f8fea59f.png)

Нужен тогда пример заполнения поля, наверное? Что туда можно написать?

**Comment by simgislab** [comment]
Re: [nextgis/docs_ngcom] Добавить раздел про CORS (#1)


да, толькл заполнить еще

http://nextgis.ru
https://nextgis.ru



Вы писали 2 июля 2017 г., 19:14:15:





Такой скриншот?
Нужен тогда пример заполнения поля, наверное? Что туда можно написать?

**Comment by Kinda-me** [comment]
https://github.com/nextgis/docs_ngcom/commit/cb9d7688bc4ced97edef98064a9386abb1496246

https://github.com/nextgis/docs_ngcom/commit/08a636fcd6e7c8b1daa5a77fe2150e5e2ad40161
